# Azure Key Vault Secret Store
# Centralized secret management with HSM-backed security
#
# Features:
#   - Hardware Security Module (HSM) protection
#   - Access policies and RBAC
#   - Secret versioning
#   - Audit logging

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: default
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  # Required: Key Vault name
  - name: vaultName
    value: "{vault-name}"

  # Authentication: Managed Identity (Recommended)
  - name: azureClientId
    value: "{managed-identity-client-id}"

  # Alternative: Service Principal
  # - name: azureTenantId
  #   value: "{tenant-id}"
  # - name: azureClientId
  #   value: "{client-id}"
  # - name: azureClientSecret
  #   secretKeyRef:
  #     name: keyvault-secrets
  #     key: client-secret

  # Alternative: Azure CLI credentials (local development)
  # - name: azureEnvironment
  #   value: "AZUREPUBLICCLOUD"

# Usage - Reference in other components:
# spec:
#   metadata:
#   - name: connectionString
#     secretKeyRef:
#       name: my-secret-name     # Secret name in Key Vault
#       key: my-secret-name      # Same as name for Key Vault

# Usage - Get secret via API:
# curl http://localhost:3500/v1.0/secrets/secretstore/my-secret-name

# Python SDK:
# from dapr.clients import DaprClient
#
# with DaprClient() as client:
#     # Get single secret
#     secret = client.get_secret(store_name="secretstore", key="my-secret-name")
#     print(secret.secret)
#
#     # Get bulk secrets
#     secrets = client.get_bulk_secret(store_name="secretstore")
#     for name, value in secrets.secrets.items():
#         print(f"{name}: {value}")

# Local development:
# Use Azure CLI authentication - ensure you're logged in:
# az login
# az account set --subscription {subscription-id}

# Azure CLI setup:
# az keyvault create --name {vault-name} --resource-group {rg} --location {location}
# az keyvault secret set --vault-name {vault-name} --name my-secret --value "secret-value"

# Managed Identity setup:
# IDENTITY_ID=$(az identity show --name dapr-identity --resource-group {rg} --query principalId -o tsv)
#
# Option 1: Access Policy (classic)
# az keyvault set-policy --name {vault-name} --object-id $IDENTITY_ID --secret-permissions get list
#
# Option 2: RBAC (recommended)
# KEYVAULT_ID=$(az keyvault show --name {vault-name} --resource-group {rg} --query id -o tsv)
# az role assignment create --role "Key Vault Secrets User" --assignee $IDENTITY_ID --scope $KEYVAULT_ID

# Secret scoping (limit which secrets can be accessed):
# Add to component metadata:
#   - name: nestedSeparator
#     value: "--"
# Then reference: my-app--database-password

---
# Using Key Vault secrets in other components:
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
  - name: url
    value: "https://{account}.documents.azure.com:443/"
  - name: masterKey
    secretKeyRef:
      name: cosmos-master-key  # References Key Vault secret
      key: cosmos-master-key
auth:
  secretStore: secretstore  # Use the Key Vault secret store
