# MySQL Binding
# Execute SQL queries and commands against MySQL/MariaDB
#
# Output binding only - execute queries
# Operations: exec (DDL/DML), query (SELECT), close

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mysql-db
  namespace: default
spec:
  type: bindings.mysql
  version: v1
  metadata:
  # Required: Connection string
  - name: url
    secretKeyRef:
      name: mysql-secrets
      key: connection-string
  # Format: "user:password@tcp(localhost:3306)/mydb?allowNativePasswords=true"

  # Optional: Connection pool settings
  # - name: maxOpenConns
  #   value: "10"
  # - name: maxIdleConns
  #   value: "5"
  # - name: connMaxLifetime
  #   value: "30m"
  # - name: connMaxIdleTime
  #   value: "5m"

  # Optional: Timeout settings
  # - name: timeout
  #   value: "30s"
  # - name: readTimeout
  #   value: "30s"
  # - name: writeTimeout
  #   value: "30s"

# Execute INSERT/UPDATE/DELETE (exec operation):
# curl -X POST http://localhost:3500/v1.0/bindings/mysql-db \
#   -H "Content-Type: application/json" \
#   -d '{
#     "operation": "exec",
#     "metadata": {
#       "sql": "INSERT INTO users (name, email) VALUES (?, ?)",
#       "params": "[\"John Doe\", \"john@example.com\"]"
#     }
#   }'

# Execute SELECT (query operation):
# curl -X POST http://localhost:3500/v1.0/bindings/mysql-db \
#   -H "Content-Type: application/json" \
#   -d '{
#     "operation": "query",
#     "metadata": {
#       "sql": "SELECT id, name, email FROM users WHERE id = ?",
#       "params": "[1]"
#     }
#   }'

# Python SDK example:
# from dapr.clients import DaprClient
#
# with DaprClient() as client:
#     # Insert
#     result = client.invoke_binding(
#         binding_name="mysql-db",
#         operation="exec",
#         binding_metadata={
#             "sql": "INSERT INTO orders (product, quantity) VALUES (?, ?)",
#             "params": '["Widget", 5]'
#         }
#     )
#
#     # Query
#     result = client.invoke_binding(
#         binding_name="mysql-db",
#         operation="query",
#         binding_metadata={
#             "sql": "SELECT * FROM orders WHERE quantity > ?",
#             "params": '[3]'
#         }
#     )
#     rows = json.loads(result.data)

# Local development with Docker:
# docker run -d -p 3306:3306 \
#   -e MYSQL_ROOT_PASSWORD=secret \
#   -e MYSQL_DATABASE=mydb \
#   mysql:8

# Security notes:
# - Always use parameterized queries (?) to prevent SQL injection
# - Store connection strings in secret stores
# - Use least-privilege database users
